version: '3.4'

services:
  projectshub:
    image: projectshub
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3010:8010
    environment: 
      TZ: America/Sao_Paulo
